services:
  warehouseapp:
    build: 
      context: .
    command: bash start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_REMOTE_SECRET: 123
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./trigger.txt:/warehouse/trigger.txt
    networks:
      - ecommerce-net
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
    networks:
      - ecommerce-net
      
networks:
    ecommerce-net:
      name: ecommerce-net
      external: true